"""Create migration for access tokens

Revision ID: 6efc2e60d0bd
Revises: 1f222371088e
Create Date: 2019-02-20 16:07:01.694795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6efc2e60d0bd'
down_revision = '1f222371088e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
                    sa.Column('token', sa.String(length=100), nullable=False),
                    sa.Column('date_created', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('token')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    # ### end Alembic commands ###
