"""empty message

Revision ID: 92d9606e980b
Revises: dc2c4910814b
Create Date: 2019-04-04 12:31:09.810109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92d9606e980b'
down_revision = 'dc2c4910814b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pathways_programs', sa.Column('apprenticeship_paid_training', sa.Boolean(), nullable=False))
    op.add_column('pathways_programs', sa.Column('phone_number', sa.String(length=32), nullable=False))
    op.add_column('pathways_programs', sa.Column('program_accredition_body', sa.String(length=1024), nullable=True))
    op.add_column('pathways_programs', sa.Column('program_city', sa.String(length=1024), nullable=False))
    op.add_column('pathways_programs', sa.Column('program_code', sa.String(length=32), nullable=True))
    op.add_column('pathways_programs', sa.Column('program_format', sa.String(length=256), nullable=True))
    op.add_column('pathways_programs', sa.Column('program_timing', sa.String(length=256), nullable=True))
    op.add_column('pathways_programs', sa.Column('regional_accredition_body', sa.String(length=1024), nullable=True))
    op.add_column('pathways_programs', sa.Column('salary_post_graduation', sa.Float(), nullable=True))
    op.alter_column('pathways_programs', 'cost_of_books_and_supplies',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pathways_programs', 'credential_earned',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('pathways_programs', 'major',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('pathways_programs', 'program_address',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    op.alter_column('pathways_programs', 'program_description',
               existing_type=sa.VARCHAR(length=4096),
               nullable=True)
    op.alter_column('pathways_programs', 'program_length',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('pathways_programs', 'provider_url',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('pathways_programs', 'salary_paid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('pathways_programs', 'provider_longitude')
    op.drop_column('pathways_programs', 'is_preparation')
    op.drop_column('pathways_programs', 'financial_aid3')
    op.drop_column('pathways_programs', 'accreditation_name')
    op.drop_column('pathways_programs', 'provider_address')
    op.drop_column('pathways_programs', 'financial_aid1')
    op.drop_column('pathways_programs', 'financial_aid5')
    op.drop_column('pathways_programs', 'financial_aid4')
    op.drop_column('pathways_programs', 'provider_latitude')
    op.drop_column('pathways_programs', 'financial_aid2')
    op.drop_column('pathways_programs', 'is_occupational_requirement')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pathways_programs', sa.Column('is_occupational_requirement', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('pathways_programs', sa.Column('financial_aid2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pathways_programs', sa.Column('provider_latitude', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pathways_programs', sa.Column('financial_aid4', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pathways_programs', sa.Column('financial_aid5', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pathways_programs', sa.Column('financial_aid1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pathways_programs', sa.Column('provider_address', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.add_column('pathways_programs', sa.Column('accreditation_name', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.add_column('pathways_programs', sa.Column('financial_aid3', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pathways_programs', sa.Column('is_preparation', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('pathways_programs', sa.Column('provider_longitude', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('pathways_programs', 'salary_paid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pathways_programs', 'provider_url',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('pathways_programs', 'program_length',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('pathways_programs', 'program_description',
               existing_type=sa.VARCHAR(length=4096),
               nullable=False)
    op.alter_column('pathways_programs', 'program_address',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    op.alter_column('pathways_programs', 'major',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('pathways_programs', 'credential_earned',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('pathways_programs', 'cost_of_books_and_supplies',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('pathways_programs', 'salary_post_graduation')
    op.drop_column('pathways_programs', 'regional_accredition_body')
    op.drop_column('pathways_programs', 'program_timing')
    op.drop_column('pathways_programs', 'program_format')
    op.drop_column('pathways_programs', 'program_code')
    op.drop_column('pathways_programs', 'program_city')
    op.drop_column('pathways_programs', 'program_accredition_body')
    op.drop_column('pathways_programs', 'phone_number')
    op.drop_column('pathways_programs', 'apprenticeship_paid_training')
    # ### end Alembic commands ###
